### PR TITLE
Add authentication to utsouthwestern microsoft.

### LINKED ISSUE #19: switch to UTSW Ldap server

### PR DESCRIPTION
**Pull request by vsmalladi**
Close #19

### CODE REVIEW

**Comment by mingjiecn** [comment]
Redirect page after log in needs to be corrected. 
image

**Comment by SenseCode** [comment]
1. Can log in with or without vpn.
2. Some data cannot load, guest test data issue with users, hope won't happen with real data. 
image
3. Dictionary and some of other page cannot open(Cause 2?)
Working great elsewise.

**Comment by SenseCode** [comment]
Double checked, no vpn log in needed and no login twice needed.

**Comment by vsmalladi** [comment]
@mingjiecn and @SenseCode fixed issues. Can you test again?

**Review by SenseCode — APPROVED** [review]
All loaded, and callback issue got fixed, great work! @vsmalladi

**Pull request merged**
