### PR TITLE
Consent genomic

### LINKED ISSUE #112: figure out how to embed patient into biospecimen

### PR DESCRIPTION
**Pull request by SenseCode**
- [x] Default item_status is `revoked` and genomic_release is `N`.

- [x] Updated show page status

- [x] Hide genomic table when revoked.

- [x] Embed in biospecimen page shows issues when test consent type.

### CODE REVIEW

**Comment by SenseCode** [comment]
Future will manually write a script to default set biofile status with restricted, so we made the following changes:
- [x] Remove genomic_release from Biofile.py.

- [x] Add restricted status in object status.

- [x] Test biofile inserts with restricted status.

**Review by vsmalladi — CHANGES_REQUESTED** [review]
@SenseCode @mingjiecn 

Bioexperiments doesn't seem to render it is looking for an accession for KCEBE765UIY

Everything else looks good.

**Comment by vsmalladi** [comment]
@SenseCode looks like its because biospecimen_summary is empty

**Comment by vsmalladi** [comment]
Close #390
Close #395
Close #391

**Comment by vsmalladi** [comment]
Close #397, merged into this one

**Review by vsmalladi — APPROVED** [review]

**Pull request merged**
