### PR TITLE
surgical and pathology reformt

### LINKED ISSUE #333: link between surgery procedure and path report
Right now the data is linked this way: The surgery procedures are linked to the surgery and the path reports are linked to the surgery too. But there is no direct link between surgery procedure and path report.
If some time surgery procedure info is missing but we have path report info for this surgery, is it possible that we create a procedure type which is "Not available", then we can still have this link surgery -> surgery procedure -> path report

### PR DESCRIPTION
**Pull request by vsmalladi**
Reformat surgery and pathology linkage to make it eaiser

Close #333

### CODE REVIEW

**Comment by mingjiecn** [comment]
Started: http://localhost:8000
CREATE MAPPING RUNNING
Traceback (most recent call last):
  File "bin/dev-servers", line 112, in <module>
    sys.exit(snovault.dev_servers.main())
  File "/home/mingjie/pandiseased/develop/snovault/src/snovault/dev_servers.py", line 105, in main
    create_mapping.run(app)
  File "/home/mingjie/pandiseased/develop/snovault/src/snovault/elasticsearch/create_mapping.py", line 505, in run
    mapping = es_mapping(type_mapping(registry[TYPES], collection.type_info.item_type))
  File "/home/mingjie/pandiseased/develop/snovault/src/snovault/elasticsearch/create_mapping.py", line 466, in type_mapping
    new_mapping = new_mapping[prop]['properties']
KeyError: 'pathology_report'

**Comment by mingjiecn** [comment]
Still has the same error after latest commit.

**Comment by SenseCode** [comment]
Only need to fix this issue, otherwise works great!

image

**Review by SenseCode — APPROVED** [review]
Tested, works great now.

**Pull request merged**
