### PR TITLE
Cohort fixes 

### LINKED ISSUE #318: cohort related bugs in branch 315
- If logged in, you can't add Bioexperiment to cohort. The orange circle on cohort icon will keep spinning.
image

- in the cohort view, there is a label called "NAN OF 3", and click the arrows around this label has no event triggered.
image

- The tooltip for add the bioexperiment is wrong:
image

### LINKED ISSUE #320: Can't add or remove a specific patient on patient search view page. Can only add all in search view
Can't add or remove a single patient on patient search view page. Can only add all in search view.
image

### LINKED ISSUE #342: Change Datasets/Experimments to just Experiments serach

### LINKED ISSUE #343: Change order of serach of data drop down
Move pathology/sugery search about biospeciments

### PR DESCRIPTION
**Pull request by vsmalladi**
Close #318 
Close #343
Close #342
Close #320

### CODE REVIEW

**Comment by mingjiecn** [comment]
Without log in, after add one experiment to cohort, the cohort view is empty:
image
if logged in, cohort icon will keep spinning, the cohort view is still empty:
image

**Review by mingjiecn — CHANGES_REQUESTED** [review]
can't add experiment after logged in

**Comment by SenseCode** [comment]
- [ ]  Before user to sign in, we can add patient/biospecimen/bioexperiment to cohort, but cohort view won't show bioexperiment. We can clear the cohort. 

image

- [ ] If sign in, we can add patient/biospecimen/bioexperiment separately to cohort, but cohort view will only show patient data. Biospecimen and bioexperiment linking with cohort are broken. And clear cohort button won't work. 

image
image

- [ ] simple facets in the left should we rearrange and fit them in?

**Comment by vsmalladi** [comment]
Okay i think i found the issue and this is a limitation of the cohort builder. We may not be able to do patient and BioExperiment cohort building at the same time.

**Comment by mingjiecn** [comment]
The tooltip for add patient is "add patient from cohort", should it be "add patient to cohort"?
The website seems to run smoothly, but I got error on the server console. I had similar error previously as well.
image

**Review by mingjiecn — APPROVED** [review]

**Pull request merged**
