### PR TITLE
341 update tooltips

### LINKED ISSUE #323: Update data organization page and definition page for Bioexperiment, bioseries and biofileset

### LINKED ISSUE #341: Add/update tooltips and definitions

### LINKED ISSUE #363: Add dictionary/document page to help tab
As topic, will be convenience for user to understand what the terms' meaning in our website.

### PR DESCRIPTION
**Pull request by SenseCode**
close #341 
close  #363 

image

image

### CODE REVIEW

**Review by mingjiecn — APPROVED** [review]

**Review by vsmalladi — CHANGES_REQUESTED** [review]
Will need to add all tooltips for Biospecimen and experiemnt too

**Comment by SenseCode** [comment]
Will add :
Biological replication,Technical replication, Isogenic replication,Anisogenic replication, Sequencing replication in tooltips.

**Comment by mingjiecn** [comment]
Biospecimen tooltip is in #363

**Comment by SenseCode** [comment]
Add bioexperiment part  in dictionary page
Close #323 

image

**Comment by mingjiecn** [comment]
image

**Review by vsmalladi — APPROVED** [review]
Looks great

**Pull request merged**
